#------------------------------------------------------------------------------#
# Site settings

title: Stop Australia's Data Retention Bill
email: admin@stopthespies.org
description: Innocent or not, you will be spied on if Australia's bill passes. Under the new data retention proposal, records of everything you do online or on your phone would be collected and stored. But we can stop it.
baseurl: ""
github_username:  stopthespies

# :TODO: point to live site after validating social tags
url: http://stage.stopthespies.org
domain: stage.stopthespies.org

#------------------------------------------------------------------------------#
# realtime server config

enable_realtime_features: 1         # set to false to disable socket connections
realtime_connection_timeout: 1000   # ms to wait before giving up on socket connection and falling back to AJAX. This does not necessarily mean the socket can't be connected, just that it's taking a while.

#------------------------------------------------------------------------------#
# API urls and endpoints

api_url: https://test.stopthespies.org/api:443
tweets_read_path: /tweets
stats_read_path: /stats
shares_read_path: /shares
send_email_path: /email
log_path: /log

legislators_locator_url : https://test.stopthespies.org/legislators

#------------------------------------------------------------------------------#
# social metadata

twitter_username: stopthespies
facebook_username: stopthespiesaustralia
# facebook_admin_userid :
# facebook_app_id :

# :TODO: final image paths should be relative URLs via `| prepend: site.baseurl`
share_twitter_card: summary_large_image
share_image_twitter: http://dummyimage.com/450x250/049/fff		# Sizing for large image card (summary_large_image) - requires approval
#share_image_twitter: http://dummyimage.com/280x150/049/fff		# Sizing for standard summary card (summary)
share_image_facebook: http://dummyimage.com/1200x1200/009/fff
share_image_gplus: http://dummyimage.com/800x600/900/fff


#------------------------------------------------------------------------------#
# Build settings
markdown: kramdown
permalink: pretty

sass:
    sass_dir: css/_sass
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
  cache: false

  # --- DEV ---

  js_compressor:  ~
  css_compressor: ~
  cachebust: none
  gzip: false
  debug: true

  # --- PROD :TODO: enable for launch ---

  # js_compressor: uglifier
  # css_compressor: ~
  # cachebust: hard
